import {City,DT} from './engine.mjs';import {Run,requestDecision} from './runner.mjs';import {CityView} from './scene.mjs';
const $=id=>document.getElementById(id);let view;
try{view=new CityView($('viewport'));}catch(e){$('status').textContent='WebGL unavailable: '+e.message;throw e;}
let city=new City(),run=null,manual=false,manualFrames=[],live=false,recording=null,replayIndex=0,replayPlaying=false,last=performance.now(),acc=0,manualLastFrame=0;
const keys=new Set();
function method(){const d=$('driver').value;$('method').textContent=d==='direct'?'Direct controls: Jev chooses steering and pedals. No corrective autopilot.':d==='maneuver'?'Assisted maneuvers: Jev chooses direction and target speed. Code follows the lane and executes turns.':'Manual controls: you drive with WASD or the arrow keys. This is not a Jev run.';$('start').disabled=d!=='manual'&&!live;$('timing').disabled=d==='manual';}
async function connect(){try{const r=await fetch('api/status');if(!r.ok)throw Error();live=(await r.json()).live;}catch{}$('connection').textContent=live?'Live Jev available · jev-1.13.0':'Public viewer · replay recordings or drive manually. Live Jev requires the local server.';method();}
function lock(v){for(const id of ['driver','challenge','timing','seed'])$(id).disabled=v;}
function state(){return recording?(replayIndex===recording.frames.length-1?recording.final:recording.frames[replayIndex]):city.snapshot();}
function refresh(s){view.render(s);$('speed').textContent=Math.round(s.car.speed*3.6);$('clock').textContent=s.t.toFixed(1)+' s';$('distance').textContent=Math.round(s.distance)+' m';$('collisions').textContent=s.collisions;$('redlights').textContent=s.redLights;}
function decision(row){const outer=document.createElement('div');outer.className='decision';const title=document.createElement('b');title.textContent=`${row.observation_time.toFixed(1)}s → ${Object.values(row.answers||{}).join(' / ')||'Request failed'}${row.applied?'':' · not applied'}`;outer.append(title);const age=document.createElement('div');age.textContent=`Observation age ${row.observation_age_s.toFixed(2)}s`;outer.append(age);for(const call of row.result.calls){const q=Object.keys(call.payload?.questions||{})[0]||'question',u=call.response?.usage;const el=document.createElement('div');el.className='tokens';el.textContent=`${q}: ${u?u.input_tokens+' input · '+u.output_tokens+' output tokens':'usage unavailable'} · ${Math.round(call.latency_ms||0)} ms`;outer.append(el);}if(!$('stream').querySelector('.decision'))$('stream').textContent='';$('stream').prepend(outer);while($('stream').children.length>8)$('stream').lastElementChild.remove();$('latency').textContent=Math.round(row.wall_latency_ms)+' ms';}
function stop(){if(run?.active)run.stop();manual=false;replayPlaying=false;$('start').textContent='Start drive';lock(false);method();}
$('start').onclick=()=>{if(run?.active||manual){stop();return;}if(run?.pending){$('status').textContent='Waiting for previous response to finish';return;}recording=null;replayPlaying=false;document.querySelector('.playback').hidden=true;const seed=Number($('seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295){$('connection').textContent='Seed must be an integer from 0 to 4294967295.';return;}const config={seed,challenge:$('challenge').value,driver:$('driver').value,timing:$('timing').value};$('stream').textContent='Decisions appear here during a run.';$('latency').textContent='—';if(config.driver==='manual'){run=null;city=new City(config);manual=true;manualFrames=[city.snapshot()];manualLastFrame=0;}else{run=new Run(config,requestDecision,{onDecision:decision});city=run.city;}acc=0;last=performance.now();lock(true);$('start').disabled=false;$('start').textContent='Stop drive';};
$('driver').onchange=method;for(const id of ['follow','map'])$(id).onclick=()=>{view.mode=id;for(const name of ['follow','map'])$(name).classList.toggle('selected',name===id);};
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('export').onclick=()=>{const data=recording||run?.export()||{schema:'jev-city-v1',config:{driver:manualFrames.length?'manual':'preview'},final:city.snapshot(),frames:manualFrames};download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'jev-city-run.json');};
$('capture').onclick=()=>{view.render(state());const a=document.createElement('a');a.href=view.capture();a.download='jev-city-frame.png';a.click();};
addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){keys.add(e.key);if(manual)e.preventDefault();}});addEventListener('keyup',e=>keys.delete(e.key));addEventListener('blur',()=>keys.clear());
document.addEventListener('visibilitychange',()=>{if(document.hidden&&(run?.active||manual)){if(run?.active)run.stop('tab_hidden');if(manual)city.status='tab_hidden';manual=false;keys.clear();lock(false);$('start').textContent='Start drive';method();}});
async function recordings(){try{const r=await fetch('records/index.json');if(!r.ok)throw Error();const list=await r.json();$('recording').replaceChildren(...list.map(item=>{const o=document.createElement('option');o.value=item.path;o.textContent=item.label;return o;}));if(!list.length)throw Error();}catch{$('recording').innerHTML='<option value="">No published recordings yet</option>';$('replay').disabled=true;}}
$('replay').onclick=async()=>{if(recording){if(replayIndex===recording.frames.length-1){replayIndex=0;lastRecorded=-1;acc=0;}replayPlaying=!replayPlaying;$('replay').textContent=replayPlaying?'Pause recording':'Resume recording';return;}stop();try{const r=await fetch($('recording').value);if(!r.ok)throw Error('Recording not found');recording=await r.json();lastRecorded=-1;replayIndex=0;replayPlaying=true;acc=0;document.querySelector('.playback').hidden=false;$('seek').max=recording.frames.length-1;$('replay').textContent='Pause recording';$('method').textContent=`Recorded Jev · ${recording.config.driver==='maneuver'?'assisted maneuvers':'direct controls'} · ${recording.config.timing} · seed ${recording.config.seed}. No live API calls.`;$('stream').textContent='Recorded decisions appear as playback advances.';}catch(e){$('status').textContent=e.message;}};
$('recording').onchange=()=>{recording=null;replayPlaying=false;$('replay').textContent='Play recording';document.querySelector('.playback').hidden=true;method();};
$('seek').oninput=()=>{replayIndex=Number($('seek').value);replayPlaying=false;$('replay').textContent='Resume recording';showRecordedDecision();};
let lastRecorded=-1;function showRecordedDecision(){const t=recording.frames[replayIndex].t;const row=recording.decisions.findLast(r=>r.application_time<=t);if(row&&lastRecorded!==row.index){lastRecorded=row.index;decision(row);}}
function animate(now){const elapsed=(now-last)/1000;last=now;
 if(run?.active){run.update();$('status').textContent=run.pending?(run.config.timing==='paused'?'World paused · awaiting Jev':'City moving · awaiting Jev'):'Jev driving';}
 else if(manual){acc+=elapsed;while(acc+1e-9>=DT&&city.status==='running'){city.setAction({steer:(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),throttle:keys.has('w')||keys.has('ArrowUp')?1:0,brake:keys.has('s')||keys.has('ArrowDown')?1:0});city.step();acc-=DT;if(city.tick-manualLastFrame>=2){manualFrames.push(city.snapshot());manualLastFrame=city.tick;}}$('status').textContent='You are driving · WASD / arrows';if(city.status!=='running'){manual=false;stop();}}
 if(recording){if(replayPlaying){acc+=elapsed;while(replayIndex<recording.frames.length-1&&acc>=recording.frames[replayIndex+1].t-recording.frames[replayIndex].t){acc-=recording.frames[replayIndex+1].t-recording.frames[replayIndex].t;replayIndex++;}if(replayIndex===recording.frames.length-1){replayPlaying=false;$('replay').textContent='Resume recording';}}$('seek').value=replayIndex;$('replaytime').textContent=recording.frames[replayIndex].t.toFixed(1)+' s';$('status').textContent='Recorded Jev · '+(replayPlaying?'playing':'paused');showRecordedDecision();}
 else if(!run?.active&&!manual&&city.status!=='running'){$('status').textContent=city.status.replaceAll('_',' ')+' · '+city.stops+'/'+city.goals.length+' stops';if($('start').textContent==='Stop drive')stop();}
 refresh(state());requestAnimationFrame(animate);
}
connect();recordings();requestAnimationFrame(animate);

let comparison=[];
function compare(){const challenge=$('challenge').value;$('comparison-body').replaceChildren(...comparison.filter(r=>r.run.startsWith(challenge+'-')).map(r=>{const tr=document.createElement('tr');const label=r.run.slice(challenge.length+1).replace('maneuver','Assisted maneuvers').replace('direct','Direct controls').replace('-paused',' / paused').replace('-realtime',' / real time');for(const value of [label,r.status.replaceAll('_',' '),r.distance_m.toFixed(1)+' m',String(r.stops),r.median_observation_age_s.toFixed(2)+' s']){const td=document.createElement('td');td.textContent=value;tr.append(td);}return tr;}));}
$('challenge').addEventListener('change',compare);
fetch('records/pilot-v2/analysis.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{comparison=d.runs;compare();}).catch(()=>{$('compare-note').textContent='Pilot results are not yet available.';});
