import test from 'node:test';import assert from 'node:assert/strict';
import {City,signal,payloads,applyAnswers} from './engine.mjs';import {Run} from './runner.mjs';
test('seeded traffic and physics are reproducible',()=>{const a=new City(),b=new City();for(const c of [a,b]){c.setAction({steer:0,throttle:.7,brake:0});c.advance(3);}assert.deepEqual(a.snapshot(),b.snapshot());assert(a.distance>0);assert.equal(a.car.x,3.5);});
test('controls execute without an automatic curb safety filter',()=>{const c=new City();c.traffic=[];c.setAction({steer:1,throttle:1,brake:0});c.advance(12);assert.equal(c.status,'collision');assert.equal(c.collisions,1);const t=c.t;c.advance(4);assert.equal(c.t,t);});
test('traffic collision terminates',()=>{const c=new City();c.traffic=[{id:0,...c.car}];c.step();assert.equal(c.status,'collision');assert.equal(c.events[0].type,'traffic_collision');});
test('stopped target counts, passing fast does not',()=>{const c=new City();c.traffic=[];c.car={x:58,z:3.5,heading:Math.PI/2,speed:5};c.step();assert.equal(c.stops,0);c.car.speed=0;c.step();assert.equal(c.status,'completed');});
test('red-light entry counts once and green entry is legal',()=>{for(const [tick,count] of [[260,1],[0,0]]){const c=new City();c.traffic=[];c.tick=tick;c.t=tick*.05;c.car={x:3.5,z:7.1,heading:0,speed:4};c.advance(.2);assert.equal(c.redLights,count);}});
test('traffic lights have an all-red gap',()=>{assert.equal(signal(11,0,0,'x'),'red');assert.equal(signal(11,0,0,'z'),'red');assert.equal(signal(13,0,0,'x'),'green');});
test('questions use same state but independent token-accountable calls',()=>{const o=new City().observation(),p=payloads(o,'direct');assert.equal(p.length,2);assert(p.every(x=>Object.keys(x.questions).length===1));assert.deepEqual(p[0].state,p[1].state);assert(!JSON.stringify(o).includes('optimal'));});
test('invalid controls rejected, model choice mapped exactly',()=>{const c=new City();applyAnswers(c,'direct',{steering:'left',pedals:'brake'});assert.deepEqual(c.action,{steer:-.3,throttle:0,brake:.8});assert.throws(()=>applyAnswers(c,'direct',{steering:'oops',pedals:'brake'}));});
function response(){return {valid:true,calls:[{response:{answers:{steering:{choice:'straight'}}}},{response:{answers:{pedals:{choice:'accelerate'}}}}]};}
for(const mode of ['paused','realtime'])test(mode+' obeys the API-wait timing contract',async()=>{let clock=0,resolve;const run=new Run({timing:mode},()=>new Promise(r=>resolve=r),{now:()=>clock});run.city.traffic=[];run.city.setAction({steer:0,throttle:.7,brake:0});run.update();clock=1000;run.update();assert(Math.abs(run.city.t-(mode==='paused'?0:1))<1e-8);resolve(response());await new Promise(r=>setImmediate(r));const d=run.decisions[0];assert(Math.abs(d.observation_age_s-(mode==='paused'?0:1))<1e-8);assert(d.applied);assert(Math.abs(run.city.t-(mode==='paused'?.6:1))<1e-8);});
test('API failure stops without fallback',async()=>{const r=new Run({timing:'paused'},async()=>({valid:false,calls:[]}));r.update();await new Promise(r=>setImmediate(r));assert.equal(r.city.status,'api_error');assert.equal(r.city.t,0);assert.equal(r.decisions[0].applied,false);});
test('late response after stop never applies',async()=>{let resolve;const r=new Run({timing:'paused'},()=>new Promise(x=>resolve=x));r.update();r.stop();resolve(response());await new Promise(x=>setImmediate(x));assert.equal(r.decisions[0].applied,false);});
test('assisted lane controller is explicit and centers straight driving',()=>{const c=new City();c.traffic=[];c.setManeuver({direction:'north',speed:4});c.advance(4);assert.equal(c.car.x,3.5);assert(c.distance>10);assert(c.car.speed<4.1);});
for(const direction of ['east','west'])for(const speed of [4,8])test(`assisted ${direction} turn at ${speed}m/s clears the curb`,()=>{const c=new City();c.traffic=[];c.setManeuver({direction,speed});c.advance(speed===4?24:12);assert.equal(c.status,'running');assert(Math.abs(c.car.z-(direction==='east'?3.5:-3.5))<1);});
test('v2 following traffic does not rear-end a stationary ego in its initial lane',()=>{const c=new City();c.advance(8);assert.equal(c.status,'running');const behind=c.traffic.find(o=>o.id===4);assert(behind.z-c.car.z>3.6);assert(behind.speed<.5);});
test('known assisted trajectory can reach and stop at the destination without traffic',()=>{const c=new City();c.traffic=[];for(let i=0;i<1800&&c.status==='running';i++){c.setManeuver({direction:c.car.x>52?'stop':'east',speed:4});c.step();}assert.equal(c.status,'completed');assert.equal(c.stops,1);assert.equal(c.collisions,0);});
