'use strict';
const $=id=>document.getElementById(id), data=window.UNASSISTED_DATA;
const names={original:'Original prompt',priority:'Explicit priorities',narrative:'Prose description',ascii:'ASCII board',egocentric:'Head-relative coordinates',history:'Recent move history',absolute:'Absolute directions',review:'Two-call self-review'};
let mode='replay',selected=null,frames=[],initial=null,index=0,playing=false,busy=false,timer=null,liveId=null,server=false;
function stop(){playing=false;clearTimeout(timer);}
function message(s){$('message').textContent=s;$('message').hidden=!s;}
function state(){return index?frames[index-1].state:initial;}
function render(){
 const s=state(),d=index?frames[index-1].decision:null,ctx=$('board').getContext('2d'),cell=60;
 ctx.fillStyle='#0d3328';ctx.fillRect(0,0,720,720);ctx.strokeStyle='#355646';
 for(let i=0;i<=12;i++){ctx.beginPath();ctx.moveTo(i*cell,0);ctx.lineTo(i*cell,720);ctx.moveTo(0,i*cell);ctx.lineTo(720,i*cell);ctx.stroke();}
 const square=(p,c,inset=5)=>{ctx.fillStyle=c;ctx.fillRect(p[0]*cell+inset,p[1]*cell+inset,cell-2*inset,cell-2*inset);};
 if(s){if(s.food)square(s.food,'#f18b78',10);[...s.snake].reverse().forEach((p,i)=>square(p,i===s.snake.length-1?'#c2ff68':'#99d849'));}
 $('board').setAttribute('aria-label',s?`Classic Snake, ${s.score} foods, ${s.moves} moves, ${s.status}`:'No game started');
 $('food').textContent=s?.score??'—';$('moves').textContent=s?.moves??'—';$('latency').textContent=d?Math.round(d.latency_ms)+' ms':'—';$('tokens').textContent=d?.usage?.input_tokens??'—';
 $('board-status').textContent=s?.status.replaceAll('_',' ')||'Ready';$('arena-label').textContent='Classic · solid boundaries';$('frame').textContent=`${index} / ${frames.length} frames`;
 $('seek').max=frames.length;$('seek').value=index;$('seek').disabled=mode==='live'||busy;
 $('play').querySelector('span').textContent=playing?'Pause':busy?'Thinking…':mode==='live'?'Start live':'Play';$('play').disabled=busy&&!playing;
 $('step').disabled=busy||(mode==='replay'&&index>=frames.length)||(mode==='live'&&s&&s.status!=='playing');
 for(const id of ['controller','run','live-seed','live-mode','replay-mode'])$(id).disabled=busy;
 $('decision-source').textContent=d?(d.action?'Executed model choice: '+d.action:'API interruption · no move'):'No decision yet';
 for(const el of document.querySelectorAll('[data-action]')){const a=el.dataset.action,before=index>1?frames[index-2].state:initial,dirs=['north','east','south','west'],absolute=before?dirs[(dirs.indexOf(before.heading)+({left:-1,straight:0,right:1}[a])+4)%4]:null,p=d?.answer?.probabilities?.[a]??d?.answer?.probabilities?.[absolute];el.classList.toggle('selected',d?.action===a);el.querySelector('span').textContent=d?`${p===undefined?'No answer':Math.round(p*100)+'%'}`:'—';}
 $('decision-note').textContent=d?`${d.action?'Executed '+d.action+' without correction.':'Request failed; no move executed.'} ${d.calls.map(c=>`${c.stage}: ${c.usage?.input_tokens??'unknown'} input / ${c.usage?.output_tokens??'unknown'} output tokens`).join('; ')}. ${frames[index-1].offline_score&&d.action?'Offline score: '+(frames[index-1].offline_score.oracle_unknown?'unknown':frames[index-1].offline_score.shortest?'shortest move':'not a shortest move')+'.':''}`:'Advance to inspect the actual model choice and per-question tokens.';
 $('download').disabled=!s;
}
function load(){stop();selected=data?.runs.find(r=>r.id===$('run').value)||null;initial=selected?.initial;frames=selected?.frames||[];index=0;liveId=null;
 if(selected){$('run-note').textContent=`${names[selected.variant]} · seed ${selected.seed} · ${selected.final.score} foods in ${selected.final.moves} moves · ${selected.final.status.replaceAll('_',' ')}. Held-out study; eight-food cap.`;history.replaceState(null,'','?variant='+selected.variant+'&run='+selected.id);}render();}
function populate(){stop();const runs=data?.runs.filter(r=>r.variant===$('controller').value)||[];$('run').replaceChildren(...runs.map(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=`Seed ${r.seed} · ${r.final.score} foods`;return o;}));if(mode==='replay')load();else{frames=[];initial=null;index=0;liveId=null;render();}}
function setMode(next){if(busy)return;stop();mode=next;frames=[];initial=null;index=0;liveId=null;
 for(const m of ['replay','live']){$(m+'-mode').classList.toggle('active',mode===m);$(m+'-mode').setAttribute('aria-pressed',mode===m);}
 $('run-label').hidden=mode==='live';$('seed-label').hidden=mode!=='live';$('speed').disabled=mode==='live';$('best').hidden=mode==='live';$('mode-caption').textContent=mode==='live'?'Fresh API decisions, one move at a time.':'Frozen held-out games.';
 if(mode==='replay'){message('');load();}else{message(server?'Press Start live. Model profiles make paid API calls.':'Run locally: python -m snake_demo.unassisted.server');$('run-note').textContent='Fresh live game; excluded from the research totals.';render();}}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v;}
async function step(){if(busy)return;if(mode==='replay'){index=Math.min(index+1,frames.length);render();return;}busy=true;render();try{if(!server)throw Error('Live mode requires the unassisted server on port 8767.');if(!liveId){const seed=Number($('live-seed').value);if(!Number.isInteger(seed)||seed<0||seed>=2**32)throw Error('Invalid seed');const r=await api('/api/start',{variant:$('controller').value,seed});liveId=r.id;initial=r.state;frames=[];index=0;}const r=await api('/api/step',{id:liveId,moves:state().moves});frames.push(r);index++;message('');}catch(e){stop();message(e.message);if(initial){frames.push({state:{...state(),status:'api_error'},error:e.message});index=frames.length;}}finally{busy=false;render();}}
async function tick(){if(!playing)return;await step();if(!playing)return;if((mode==='replay'&&index>=frames.length)||(mode==='live'&&state()?.status!=='playing')){stop();render();return;}const d=index?frames[index-1].decision:null;timer=setTimeout(tick,mode==='live'?0:$('speed').value==='recorded'?Math.max(40,d?.latency_ms||80):Number($('speed').value));}
$('play').onclick=()=>{if(playing){stop();render();return;}if(busy)return;if(mode==='replay'&&index>=frames.length)index=0;if(mode==='live'&&state()?.status!=='playing'){liveId=null;frames=[];initial=null;index=0;}playing=true;tick();};
$('step').onclick=()=>{stop();step();};$('seek').oninput=()=>{stop();index=Number($('seek').value);render();};$('controller').onchange=populate;$('run').onchange=load;
$('replay-mode').onclick=()=>setMode('replay');$('live-mode').onclick=()=>setMode('live');
$('best').onclick=()=>{const r=data.runs.filter(r=>r.variant===$('controller').value).sort((a,b)=>b.final.score-a.final.score||a.final.moves-b.final.moves)[0];if(r){$('run').value=r.id;load();message('Selected highest score, then fewest moves. This is a selected example.');}};
$('download').onclick=()=>{const b=new Blob([JSON.stringify({variant:$('controller').value,initial,frames},null,2)],{type:'application/json'});const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download='classic-'+(selected?.id||'live')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
if(data){$('controller').replaceChildren(...Object.keys(data.metrics).map(v=>{const o=document.createElement('option');o.value=v;o.textContent=names[v];return o;}));if(data.preferred)$('controller').value=data.preferred;for(const [profile,m]of Object.entries(data.metrics)){const row=document.createElement('tr');for(const text of [names[profile],`${m.successes}/${m.episodes}`,m.stats.valid_decisions?`${m.stats.shortest}/${m.stats.valid_decisions}`:'No model',m.mean_food.toFixed(2)]){const td=document.createElement('td');td.textContent=text;row.append(td);}$('result-rows').append(row);}$('study-count').textContent=`${data.runs.length} held-out attempts; ${Object.values(data.metrics).reduce((n,m)=>n+m.api_interrupted_games,0)} API interruptions retained. Shortest labels are offline only. No model choice was corrected.`;const params=new URLSearchParams(location.search);if(data.metrics[params.get('variant')])$('controller').value=params.get('variant');populate();if([...$('run').options].some(o=>o.value===params.get('run'))){$('run').value=params.get('run');load();}}else{message('Unassisted dataset is not yet built.');render();}
if(['localhost','127.0.0.1'].includes(location.hostname)&&location.port==='8767')fetch('/api/config').then(r=>r.json()).then(()=>{server=true;}).catch(()=>{});
